# Generated by Django 2.2.10 on 2020-02-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200221_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucard',
            name='items',
            field=models.CharField(db_index=True, default='', max_length=120),
        ),
    ]
