# Generated by Django 2.2.10 on 2020-02-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menucard_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucard',
            options={'ordering': ['Menu_Type'], 'verbose_name': 'Menu Type', 'verbose_name_plural': 'Menu Types'},
        ),
    ]
