# Generated by Django 2.2.10 on 2020-02-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menucard_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucard',
            name='items',
        ),
    ]
