# Generated by Django 2.2.10 on 2020-02-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200220_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
    ]
