# Generated by Django 2.2.10 on 2020-02-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_menucard_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='item'),
        ),
    ]
