# Generated by Django 2.2.10 on 2020-02-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200222_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucard',
            name='items',
            field=models.CharField(db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='items'),
        ),
    ]
