# Generated by Django 2.2.10 on 2020-02-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_menucard_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucard',
            name='items',
            field=models.CharField(db_index=True, default='', max_length=120),
        ),
    ]
