# Generated by Django 2.2.10 on 2020-02-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_menucard_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucard',
            options={'ordering': ['slug'], 'verbose_name': 'Menu Type', 'verbose_name_plural': 'Menu Types'},
        ),
    ]
